### ISSUE TITLE
Video streaming

### ISSUE THREAD

**Issue by DzigaVertoff** [phoenixbf/aton#23]
I'm trying to use video streaming, but it doesn't work. Other users don't receive it. (Audio streaming works)

EDIT: also screen streaming doesn't work

EDIT2: It seems that in _ATON.photon.js_ the second parameter of _Photon.socket.on('UVIDEO') is empty

**Comment by phoenixbf** [comment]
Hi,
the UVIDEO event is an internal Photon event for transmission of video chunks (typically webcam or screen sharing) in a collaborative session, and it's still experimental feature. You can experiment this via _Hathor_ front-end when logged in, using webcam or screen sharing buttons from collaborative popup (colored icon): just tested and it seems they are working fine.
A drop-down menu for selection of input device is still missing (eg. two or more cameras) but will be soon introduced, as well as examples.

Can you please provide more details?

If you are looking for transimssion of custom data, check out: https://aton.ispc.cnr.it/apidoc/client/Photon.html#.fireEvent and https://aton.ispc.cnr.it/apidoc/client/Photon.html#.on
